### ISSUE TITLE
[micro-dash] Reduce typings incorrect (I think)

### ISSUE THREAD

**Issue by benallfree** [simontonsoftware/s-libs#20]
`key: keyof E` should be `key: keyof ObjectWith<E>`

```typescript
export declare function reduce<E>(array: ObjectWith<E> | undefined, iteratee: (accumulator: E, value: E, key: keyof ObjectWith<E>) => E): E;
export declare function reduce<E, A>(array: ObjectWith<E> | undefined, iteratee: (accumulator: A, value: E, key: keyof ObjectWith<E>) => A, accumulator: A): A;
```

**Comment by benallfree** [comment]
>  this the old repo for 

It is? This is where npm leads :/ Sorry, where is the new one?

**Comment by ersimont** [comment]
The old, deprecated package on npm is [micro-dash](https://www.npmjs.com/package/micro-dash), and this ticket was originally created over at it's repo. You'll see the deprecation notice at that link.

The new package is [@s-libs/micro-dash](https://www.npmjs.com/package/@s-libs/micro-dash), and it's repo is right here. You created this ticket at the old repo, and I transferred it over here to the new repo.

Sorry for the confusion. I moved all my open source libraries to this monorepo to simplify my life. I moved the NPM packages to sync up their version numbers, to make it easy to see/understand which versions of all the libraries go together.

**Comment by ersimont** [comment]
This should be fixed up in the next release. Thank you for the report!

**Comment by ersimont** [comment]
And the fix is now generally available in release 11.2.0

**Comment by benallfree** [comment]
Thank you @ersimont! Long live micro-dash.

**Comment by benallfree** [comment]
>  `keyof ObjectWith<E>` is going to simplify to something like `string | number`

PS, in my testing it actually does much better. If TS was able to infer the key names for a given type, each object in the collection will have full intellisense in the callback (VSCode)

**Comment by ersimont** [comment]
> Long live micro-dash.

Haha. Thanks!

> PS, in my testing it actually does much better.

I'm surprised! `type ObjectWith<T> = Record<string, T>`, which I would have thought would lead to this chain of simplifications:

```
keyof ObjectWith<E>
keyof Record<string, E>
keyof { [x: string]: E }
string
```

**Comment by benallfree** [comment]
I'm sorry, I was mistaken.

`accumulator: E, value: E` is what gives full intellisense. Yes I think the type of the 3rd parameter, `key`, is definitely just `string`
