### ISSUE TITLE
[ng-core] Make subscribeTo mirror subscribe

### ISSUE THREAD

**Issue by jrdioko** [simontonsoftware/s-libs#27]
It would be helpful for `subscribeTo` to accept anything that native `.subscribe()` can (in particular, a `BehaviorSubject`).

**Comment by ersimont** [comment]
Addressed in 4b1aad6379411a6d52c85b65a6edecca19bc7bb4. Use the new `SubscriptionManager.manage()` for this. E.g.:

```ts
subscriptionManager.manage(observable.subscribe(observer));
```
