### ISSUE TITLE
[ng-core] Provide validation errors of parent control

### ISSUE THREAD

**Issue by TobiasXy** [simontonsoftware/s-libs#35]
So, over the last days I googled a ton and basically developed something along the lines of WrappedFormControlSuperclass myself.
Now I found this library and am happy to not having to reinvent the wheel anymore.

What I'm missing though is access to validation errors of the parent form control.
What I'm doing is something like this:

```
import {WrappedFormControlSuperclass} from '@s-libs/ng-core';
import {Injector} from '@angular/core';
import {NgControl, ValidationErrors} from '@angular/forms';


export abstract class CustomWrappedFormControl<OUT, IN> extends WrappedFormControlSuperclass<OUT,IN> {
  private readonly outerControl: NgControl;

  protected constructor(injector: Injector) {
    super(injector);

    this.outerControl = injector.get(NgControl);
    this.outerControl.valueAccessor = this; // this seems to be necessary, but also gets rid of the provider stuff on the parent component
  }

  public get showError(): boolean {
    const { dirty, touched } = this.outerControl;
    return this.outerControl.invalid ? (dirty || touched) : false;
  }

  public get errors(): ValidationErrors {
    return this.outerControl.errors;
  }
}
```
I'm by no means an expert, so if this is a bad way to do stuff like that feel free to close the issue (after telling me the right way to do it :P ). Otherwise, would it be possible to move that functionality into WrappedFormControlSuperclass?

**Comment by TobiasXy** [comment]
I just noticed: This fails if the current component only wraps another CVA component, since the errors are not mirrored on the FormControl created within WrappedFormControlSuperclass. Unfortunately I have no idea how to solve this.

**Comment by ersimont** [comment]
Ah, interesting and great topic! May I ask for a sample use-case? I haven't done much with form validation, and it would help me dig in more with a specific example.

I did just try messing around with a `required` validation. If I put the `required` attribute in the template of the `WrappedFormControl` subclass, no validation errors got out to the person using it. However, if I put `required` up a level where I used `[(ngModel)]` that worked. Looks like Angular's [`RequiredValidator`](https://angular.io/api/forms/RequiredValidator) lets you put `required` on anything that uses `[(ngModel)]`.

**Comment by TobiasXy** [comment]
Sure, I can share a broken down version of what I'm trying to do. Basically I have 3 components:

1. On the lowest level a component wrapping a select element which takes a list of "Project" entities and allows to choose one of them through the select (lets call it "ProjectSelectFieldComponent")
2. On the level above the component adds async functionality, by loading a list of projects from the server and passes them to the base-project-select-field ("FullProjectSelectFieldComponent")
3. On the uppermost level a component that uses the full-project-select-field (among other fields)

It looks something like this:

```typescript
@Component({
  selector: 'app-project-select-field',
  template: `<label [textContent]="label" [htmlFor]="id"></label>
  <select [ngClass]="{'is-invalid': showError}" class="form-control" [id]="id" [formControl]="formControl">
    <option [ngValue]="null">-- Select a project --</option>
    <option *ngFor="let project of projects" [ngValue]="project">{{project.id}} - {{project.name}}</option>
  </select>
  <app-form-errors [errors]="errors" [show]="showError"></app-form-errors>`,
  providers: [provideValueAccessor(ProjectSelectFieldComponent)]
})
export class ProjectSelectFieldComponent extends WrappedFormControlSuperclass<Project, Project> {

  @Input()
  label: string;

  @Input()
  id: string;

  @Input()
  projects: Project[];

  constructor(
    injector: Injector
  ) {
    super(injector);
  }
}
```

The FullProjectSelectFieldComponent:
```typescript
@Component({
  selector: 'app-full-project-select-field',
  template: `<app-project-select-field [projects]="projects" [id]="id" [label]="label" [formControl]="formControl"></app-project-select-field>`,
  providers: [provideValueAccessor(FullProjectSelectFieldComponent)]
})
export class FullProjectSelectFieldComponent extends WrappedFormControlSuperclass<Project, Project> implements OnInit, OnDestroy {

  @Input()
  id: string;

  @Input()
  label: string;

  isLoaded = false;
  isDisabled = false;

  public projects: Project[] = [];

  private stop$ = new Subject();

  constructor(
    injector: Injector,
    private projectService: ProjectService // a service that loads projects from the server
  ) {
    super(injector);
  }

  ngOnInit(): void {
    this.evaluateDisabledState();
    this.projectService.loadAll() // doesn't really matter how it works internally, but it returns a Observable<Project[]>
      .pipe(
        takeUntil(this.stop$)
      ).subscribe(projects => {
      this.projects = projects;
      this.isLoaded = true;
      this.evaluateDisabledState();
    }, err => {
        // ... error handling ...
    });
  }

  ngOnDestroy(): void {
    this.stop$.next();
  }

  // don't take the disabled state 1:1 from parent, but also take care of whether the list of options is loaded
  setDisabledState(isDisabled: boolean) {
    this.isDisabled = isDisabled;
    this.evaluateDisabledState();
  }

  private evaluateDisabledState() {
    const disabled = this.isDisabled || !this.isLoaded;
    super.setDisabledState(disabled);
  }
}
```

The component using everything:
```typescript
@Component({
  template: `<form [formGroup]="form" (ngSubmit)="onSubmit()">
    <div class="form-group">
      <app-full-project-select-field label="Projekt" id="project-field" formControlName="project"></app-full-project-select-field>
    </div>
    <div class="form-group">
      <app-button type="submit" text="Create Record"></app-button>
    </div>
  </form>`
})
export class ParentComponent {

  form = new FormGroup({
    project: new FormControl(null, [Validators.required]),
  });

  onSubmit() {
    this.form.markAllAsTouched(); // make sure error state is shown on the form controls
    if (!this.form.valid) {
      // invalid form handling goes here
      return;
    }

    const values = this.form.value;
    // ... submit the valid values ...
  }
}
```

I removed all/most code that is not related to this issue and it doesn't really reflect the state of my code currently, so it might not work out of the box, but I hope it shows my use case.  
When you (try to) submit the form with no project selected the validation error does not propagate until the ProjectSelectFieldComponent, so no error is shown (using the app-form-errors component, which I did not specify here, but it basically just shows error messages according to the passed error parameter).

**Comment by ersimont** [comment]
I live code on Twitch on Tuesdays. I'll take a look at this during the stream. Stop by at 7:30 eastern if you're available! https://www.twitch.tv/ersimont

**Comment by ersimont** [comment]
I did some detective work and figured you might in Germany, where it was 12:30 am when I started my stream. Sorry you couldn't make it!

The standard form control API that Angular uses does not allow inner components to know which validators are registered on it. It is designed for the inner component to simply report its value, and for all validation to happen at the top level.

It looks like your goal is for an inner, reusable component to be able to display validation messages in a reusable way throughout your app. To that end I recommend NOT using `WrappedFormControlSuperclass`, but instead pass your outer `formControl` down to the inner component to use directly. For example:

```ts
@Component({
  selector: 'app-project-select-field',
  template: `
    <input [formControl]="outerControl" />
    <strong *ngIf="showError">
      Errors: {{ outerControl.errors | json }}
    </strong>
  `,
  providers: [provideValueAccessor(ProjectSelectFieldComponent)],
})
export class ProjectSelectFieldComponent {
  @Input() outerControl!: AbstractControl;

  get showError(): boolean {
    const { dirty, touched } = this.outerControl;
    return this.outerControl.invalid ? dirty || touched : false;
  }
}

@Component({
  selector: 'app-parent',
  template: `
    <form [formGroup]="form">
      <app-project-select-field
        [outerControl]="form.controls.project"
      ></app-project-select-field>
    </form>
  `,
})
export class ParentComponent {
  form = new FormGroup({
    project: new FormControl(null, [Validators.required]),
  });
}
```

**Comment by ersimont** [comment]
FYI, I think `ng-core` has something to offer that will simplify some logic you wrote using `stop$`. If you extend `DirectiveSuperclass` you can use `.subscribeTo()` from one of its ancestor classes, [`SubscriptionManager`](https://simontonsoftware.github.io/s-libs/rxjs-core/classes/subscriptionmanager.html). That will automatically unsubscribe from the project service's observable if the component is destroyed. This eliminates the boilerplate of using `stop$` and `takeUntil()`.

```ts
export class FullProjectSelectFieldComponent extends DirectiveSuperclass implements OnInit {
  constructor(
    injector: Injector,
    private projectService: ProjectService // a service that loads projects from the server
  ) {
    super(injector);
  }

  ngOnInit(): void {
    this.subscribeTo(this.projectService.loadAll(), projects => {
      this.projects = projects;
      this.isLoaded = true;
      this.evaluateDisabledState();
    });
  }
}
```

**Comment by TobiasXy** [comment]
I'm indeed from germany and was already asleep when you were streaming. I watched the VOD from twitch though and it was really helpful, I think.

I will try the approach to pass the parent form control through the layers once I get back to that project. Thank you for the help!

**Comment by TobiasXy** [comment]
That approach solves the problem with passing the validators but seems to make it hard to impossible to do anything with the values or status changes (e.g. disabled, touched).

In the middle layer of my example above I asynchronously load values to be passed to the bottom-most component.
While the data is loading, I want to set the disabled status to `true` and after loading is done, reset it to whatever the actual disabled status is at that point (see code of the FullProjectSelectFieldComponent above). That works with CVAs, but apparently not when passing the FormControl throug all layers, since values and state changes are not passed through the layers but are set immediately, no matter on what layer.

When the form is submitted I call `markAllAsTouched` in the ParentComponent to force validation errors to be shown. There doesn't even seem to be an api on FormControls to observe a change like that.

It seems to me reactive forms are not really meant to be used for complex scenarios like that. I think I will try to use template drive forms instead and see if I can make this stuff work.

**Comment by ersimont** [comment]
I see. Sounds like you may need to pass a lot of things through the layers then, to achieve all that. E.g. you could stick with the value accessor approach and additionally take `@Input() validators` to assign them to the intermediate form controls.

Or maybe you could pass the form control through and additionally take `@Input() disabled` or similar?

**Comment by TobiasXy** [comment]
I revisited this issue and since none of the solutions so far seem intuitive or easy to implement, I just use a plain `WrappedFormControlSuperclass` and add an `@Input() errors: ValidationErrors | null` to all custom form components.

On the parent component I only pass the errors to the custom form components if the corresponding control is marked as touched with a method like that:

```ts
getErrors(key: string): ValidationErrors | null {
    if (this.form.controls[key].touched) {
      return this.form.controls[key].errors;
    }
    return null;
  }

That way the parent component does all the validation and the child components just are told what errors to show.
I'm closing the issue since this is good enough for me at the moment.

**Comment by ersimont** [comment]
Hello @TobiasXy! I ran across this old issue, and realized the latest version of s-libs may better accommodate your needs. It should sync validation errors both directions now when your outer component binds to the inner one using an `NgControl` (i.e. `ngModel`, `formControl`, or `formControlName`). FYI!
