### ISSUE TITLE
[ng-core] WrappedFormControlSuperclass throws an error on IE11

### ISSUE THREAD

**Issue by DmitryEfimenko** [simontonsoftware/s-libs#42]
## Reproduction:
* create new Angular project: `ng new s-libs-ng12-ie11`
* install s-libs and extra polyfills  dependencies: `npm i @s-libs/js-core @s-libs/micro-dash @s-libs/ng-core @s-libs/rxjs-core classlist.js web-animations-js`
* in the `polyffills.ts` uncomment the imports for `classlist.js` and `web-animations-js`
* in the `.browserlist` enable IE11
* add a component `DatetimeLocal` (just like in the docs for the WrappedFormControlSuperclass)
* use that component in the `AppComponent`
* make a production build: `npm run build`
* start a simple server pointing to serve the `dist/[myproject]/`
* Open IE11
* Open Developer tools
* Observe an error:
  > ERROR TypeError: Object doesn't support property or method 'setUpOuterToInner$'

## Side notes
I realize the web ecosystem slowly moves toward the better, brighter future without IE11, but it will still take a while to get there.

**Comment by ersimont** [comment]
According to https://gs.statcounter.com/browser-market-share, IE11 is at `0.71%` of global internet usage. Given that, combined with the fact that the Angular team does not set up apps to support it by default, and that I am not set up to run CI on multiple browsers at this point, I unfortunately will say that `@s-libs` does not support IE11.
