### ISSUE TITLE
[ng-core] Ability to use WrappedFormControlSuperclass with FormGroup

### ISSUE THREAD

**Issue by KrickRay** [simontonsoftware/s-libs#51]
Due to the fact that all subscriptions occur in the constructor, formControl cannot be overwritten.

**Comment by KrickRay** [comment]
I created a PR to this: https://github.com/simontonsoftware/s-libs/pull/52

**Comment by ersimont** [comment]
This ability is coming with version 13! Thank you for the suggestion, and the implementation ideas in your PR. I commented on the PR as well. Please send any more feedback.
