### ISSUE TITLE
[app-state] more informative error message when assigning to an undefined state 

### ISSUE THREAD

**Issue by RaphiStein** [simontonsoftware/s-libs#53]
When assigning to a state that is undefined, (i.e. `store('mystate').state() === undefined`), the library produces an error that is confusing and does not actually tell me what I'm doing wrong.

i.e. 

```
store('mystate').assign(undefined)
store('mystate').assign({age: 30, name: 'joe'})
```

produces a console error saying:

```
preview-bc361a02a95aae7c3363b.js:2 TypeError: Cannot read property 'age' of undefined
    at eval (store.ts:73)
    at eval (every.ts:27)
```

**Desired behaviour**

A message saying "cannot assign to undefined property `mystate`" 
(and perhaps include the application code line number in the stack trace?)

Stackblitz link:
https://stackblitz.com/edit/typescript-qg4jq7

**Comment by ersimont** [comment]
I like your profile pic :)

Thanks for the suggestion!

**Comment by ersimont** [comment]
This will come with version 13
