### ISSUE TITLE
[rxjs-core] Feature request: Move `bindToInstance` to `SubscriptionManager`

### ISSUE THREAD

**Issue by eric-simonton-sama** [simontonsoftware/s-libs#75]

**Comment by ersimont** [comment]
I tried again in Angular 15. Still gives errors, at least when moving to `SubscriptionManager`. (Maybe it could move just up to `InjectableSuperclass`?)

**Comment by ersimont** [comment]
I'm going to forget this request, at least for now. One of the main purposes of `bindToInstance()` is to automatically manage change detection, which is only relevant in directives.
