### ISSUE TITLE
Angular app with angular 14 won't compile with mixins

### ISSUE THREAD

**Issue by njourdain** [simontonsoftware/s-libs#93]
Related issue : https://github.com/microsoft/TypeScript/issues/30355

Compiling code with a mixin that contains private or protected properties will fail with TS4094 error. As a workaround, I copied the used mixins and just made the private properties public, which is not ideal.

 I also tried setting "declaration": false in my tsconfig but there was no change.

**Comment by ersimont** [comment]
I think I'll need some more info to be able to reproduce and fix the error you encountered. For example, [here](https://github.com/ersimont/weather/blob/master/src/app/state/weather-store.ts) is an Angular 14 app of mine that uses mixins from s-libs, and it compiles.

**Comment by njourdain** [comment]
Closing this issue as I cannot reproduce
